### PR TITLE
ReplyAll functionaliy recommitting

### PR DESCRIPTION
**Pull request by Anindya007**
I have reforked the master repo and redo the changes for the ReplyAll functionality.It is working in new Gmail View too.I have checked it.Please tell me what you are getting.

### CODE REVIEW

**Comment by Vikasg7** [comment]
https://github.com/Vikasg7/UnQuote-for-Gmail/blob/master/app/cs/cs.js#L7-L16  
won't work.

**Comment by Vikasg7** [comment]
Try replying one or more times in the same thread. You will notice, it un-quotes the first reply but won't un-quote the next ones.

**Comment by Anindya007** [comment]
Hmm, I see .Thanks for pointing out what I skipped.

**Comment by Vikasg7** [comment]
Yeah, Good point. Now that, I am re-writing it, I will see if I could cover the next replies otherwise I will push an update with your commits.

**Comment by Vikasg7** [comment]
Ok, I rewrote the extension. You can test it and provide feedback. I tried your fork but it wasn't working as Google has changed it internally. Now, I am imitating the process of clicking the `...` button and removing quoted text.

**Comment by Vikasg7** [comment]
You need to refresh Gmail page after you load/reload extension.  
I pushed an update to fix reply all button and also a better way to select `Reply` and `Reply to all` buttons.  Don't forget to `git pull origin master`. 
I tried your fork, It didn't work after trying a lot. Removing `...` button won't work as Gmail recalculates the quoted text after you hit send button.  
Yes, there is a 3 seconds delay between "Click of the Send Button" and "Removal of `...` button" because sometimes `...` button takes time to show up. It could be my computer slow performance. But you can lower the delay in this [line here](https://github.com/Vikasg7/UnQuote-for-Gmail/blob/master/app/cs/cs.js#L70).  
Make sure you run `npm run watch-cs` in the command prompt (or you can run task in the VS Code from command pallet) to generate bundle.js while you make changes in the cs.js.

**Comment by Anindya007** [comment]
Actually, the problem is occuring even after refreshing the gmail page. It does not happen always during all loading/reloading times but only sometimes .Strangely after two or three tries or when I try to investigate a breakpoint, the extensions suddenly begin to respond :-p.

<blockquote>It didn't work after trying a lot. Removing ... button won't work as Gmail recalculates the quoted text after you hit send button</blockquote>  

 Yes,my fork is not working when I try to reply to the same thread repeatedly.The master build handles it gracefully.I will build on top off it in future.The solution is elegant. :+1:

**Comment by Vikasg7** [comment]
I updated the code and release v0.0.6. I did a lot of refactoring. Now it is more readable.

**Pull request closed without merging**
